name: SSH to Linux VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH key to known_hosts
        run: |
          ssh-keyscan -H 62.72.27.131 >> ~/.ssh/known_hosts

      - name: SSH into Linux VM and run command
        run: |
          ssh root@62.72.27.131 'ls'
